[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
broadcast = "broadcast"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
citrea_testnet = "${CITREA_RPC_URL}"
